{"errorMessage": "This is an exception from Python!", "errorType": "Exception", "requestId": "2a1d03e0-8c57-4237-90c2-81b8275d4f10", "stackTrace": ["  File \"/opt/python/sentry_sdk/integrations/init_serverless_sdk/__init__.py\", line 77, in sentry_lambda_handler\n    return module_loader.get_lambda_handler()(event, context)\n", "  File \"/var/task/lambda_function.py\", line 22, in handler\n    one()\n", "  File \"/var/task/lambda_function.py\", line 17, in one\n    two()\n", "  File \"/var/task/lambda_function.py\", line 12, in two\n    three()\n", "  File \"/var/task/lambda_function.py\", line 7, in three\n    raise Exception('This is an exception from Python!')\n"]}